# Generated by Django 2.2.7 on 2019-11-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0002_auto_20191110_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='imagen',
            field=models.ImageField(null=True, upload_to='pictures/peliculas/%d'),
        ),
        migrations.AlterField(
            model_name='local',
            name='tiposervicio',
            field=models.CharField(max_length=200, verbose_name='Tipo de Servicio'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(null=True, upload_to='pictures/%d'),
        ),
    ]
