# Generated by Django 2.2.7 on 2019-11-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0003_auto_20191110_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='imagen',
            field=models.ImageField(null=True, upload_to='pictures/actor/%d'),
        ),
        migrations.AlterField(
            model_name='local',
            name='imagen',
            field=models.ImageField(null=True, upload_to='pictures/local/%d'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(null=True, upload_to='pictures/pelicula/%d'),
        ),
    ]
