# Generated by Django 2.2.6 on 2019-11-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0004_auto_20191110_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=220, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=220, null=True)),
                ('username', models.CharField(blank=True, max_length=10, null=True)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['nombre'],
            },
        ),
    ]
